# Generated by Django 5.1.3 on 2024-12-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketprice',
            name='wagon_type',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
