# Generated by Django 5.1.3 on 2024-12-02 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_ticketprice_wagon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketprice',
            name='wagon_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.wagontype'),
        ),
    ]
